# Generated by Django 3.1 on 2020-11-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='portfolio_site',
            field=models.URLField(),
        ),
    ]
